### ISSUE TITLE
Where does one update their profile picture?

### ISSUE THREAD

**Issue by pelson** [Anaconda-Platform/docs.anaconda.org#252]
The UI seems to have changed recently on anaconda.org, and I'm embarrassed to say I can't find a way to change my profile picture. Any advice?

Thanks!

**Comment by ostrokach** [comment]
Any update on this? Or are profile pictures not supported yet?

**Comment by jakirkham** [comment]
Any thoughts on this? I'm also clueless as to how to change this setting.

**Comment by jakirkham** [comment]
Copied to issue ( https://github.com/Anaconda-Platform/support/issues/84 ).
