### ISSUE TITLE
Docs - Updating Profile Image is missing from docs

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/docs.anaconda.org#267]
Can we make mention here in the docs that Anaconda Cloud automatically recognizes the image you associate in your Gravatar account.

http://docs.anaconda.org/managing-account.html

To update, please configure your free gravatar account here (https://en.gravatar.com) and Anaconda-Cloud will automatically pull in the image associated with the email address you signed up in Gravatar with.

**Comment by stephenakearns** [comment]
Hi Kerry, is this something you'd be able to update quickly?

**Comment by electronwill** [comment]
OK, Gravatar info is added and live at http://docs.anaconda.org/managing-account.html .
