### ISSUE TITLE
Docs: Review and update Organizations section

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/docs.anaconda.org#271]
Reported by Phil Elson..

> Just found it. Sorry about the noise Stephen. Are you aware that the docs at http://docs.anaconda.org/using.html#Organizations are out of date?
> Thanks,
> Phil

Specific issue example:
* [ ] Under "Managing Organizations it says... 

> You can view your organizations by navigating to your organizations dashboard:
> `https://anaconda.org/organization/ORGANIZATION/dashboard`
> 

But it should actually say...

> You can view your organizations by navigating to "Group Membership" which lists all the organizations/groups you belong to:
> `https://anaconda.org/<USERNAME>/groups`
> 

Steve can be the subject matter expert for questions.

**Comment by kerrywatson1** [comment]
https://github.com/ContinuumIO/anaconda-cloud-docs/pull/17
